# -*- mode: ruby -*-
# vi: set ft=ruby :

# All Vagrant configuration is done below. The "2" in Vagrant.configure
# configures the configuration version (we support older styles for
# backwards compatibility). Please don't change it unless you know what
# you're doing.
Vagrant.configure("2") do |config|
  # The most common configuration options are documented and commented below.
  # For a complete reference, please see the online documentation at
  # https://docs.vagrantup.com.

  # Every Vagrant development environment requires a box. You can search for
  # boxes at https://atlas.hashicorp.com/search.
  config.vm.box = "ubuntu/xenial64"

  #config.ssh.insert_key = false
  # config.ssh.private_key_path = ["keys/private_key"]

  #config.ssh.username = "vagrant"
  #config.ssh.password = "vagrant"

  config.vm.network :forwarded_port, guest: 8020, host: 8020
  config.vm.network :forwarded_port, guest: 8021, host: 8021
  config.vm.network :forwarded_port, guest: 9911, host: 9911
  config.vm.network :forwarded_port, guest: 9998, host: 9998
  config.vm.network :forwarded_port, guest: 6698, host: 6698
  config.vm.network :forwarded_port, guest: 6699, host: 6699
  config.vm.network :forwarded_port, guest: 2020, host: 2020
  config.vm.network :forwarded_port, guest: 2021, host: 2021
  config.vm.network :forwarded_port, guest: 8041, host: 8041
  config.vm.network :forwarded_port, guest: 8043, host: 8043

  # Disable automatic box update checking. If you disable this, then
  # boxes will only be checked for updates when the user runs
  # `vagrant box outdated`. This is not recommended.
  # config.vm.box_check_update = false

  # Create a forwarded port mapping which allows access to a specific port
  # within the machine from a port on the host machine. In the example below,
  # accessing "localhost:8080" will access port 80 on the guest machine.
  # config.vm.network "forwarded_port", guest: 80, host: 8080

  # Create a private network, which allows host-only access to the machine
  # using a specific IP.
  # config.vm.network "private_network", ip: "192.168.33.10"

  # Create a public network, which generally matched to bridged network.
  # Bridged networks make the machine appear as another physical device on
  # your network.
  config.vm.network "public_network", ip: "172.18.131.21"
  # config.vm.network "public_network", use_dhcp_assigned_default_route: true

  # Share an additional folder to the guest VM. The first argument is
  # the path on the host to the actual folder. The second argument is
  # the path on the guest to mount the folder. And the optional third
  # argument is a set of non-required options.
  # config.vm.synced_folder "../data", "/vagrant_data"

  # Provider-specific configuration so you can fine-tune various
  # backing providers for Vagrant. These expose provider-specific options.
  # Example for VirtualBox:
  #
   config.vm.provider "virtualbox" do |vb|
     # Display the VirtualBox GUI when booting the machine
     vb.gui = true

     # Customize the amount of memory on the VM:
     vb.memory = 8096
	 vb.cpus = 4
   end
   #
  # View the documentation for the provider you are using for more
  # information on available options.

  # Define a Vagrant Push strategy for pushing to Atlas. Other push strategies
  # such as FTP and Heroku are also available. See the documentation at
  # https://docs.vagrantup.com/v2/push/atlas.html for more information.
  # config.push.define "atlas" do |push|
  #   push.app = "YOUR_ATLAS_USERNAME/YOUR_APPLICATION_NAME"
  # end

  # Enable provisioning with a shell script. Additional provisioners such as
  # Puppet, Chef, Ansible, Salt, and Docker are also available. Please see the
  # documentation for more information about their specific syntax and use.
  config.vm.provision "shell", path: "provisioning_puppetagent_ubuntu.sh"
  config.vm.provision "file", source: "up_puppetagent.sh", destination: "~/up_puppetagent.sh"
  config.vm.provision "shell", inline: "sudo -H -u ubuntu bash -c 'chmod +x ~/up_puppetagent.sh'"
  config.vm.provision "file", source: "php_oneagent_init.sh", destination: "~/php_oneagent_init.sh"
  config.vm.provision "shell", inline: "sudo -H -u ubuntu bash -c 'chmod +x ~/php_oneagent_init.sh'"

#config.vm.provision "shell" do |s|
#  ssh_pub_key = File.readlines("keys/private_key.pub").first.strip
#  s.inline = <<-SHELL
#    echo #{ssh_pub_key} >> /home/vagrant/.ssh/authorized_keys
#    echo #{ssh_pub_key} >> /root/.ssh/authorized_keys
#  SHELL
#end


end
